/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as InterventionVilleRouteImport } from './routes/intervention.$ville'
import { Route as LiveTrackingIdRouteImport } from './routes/live-tracking.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionVilleRoute = InterventionVilleRouteImport.update({
  id: '/intervention/$ville',
  path: '/intervention/$ville',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTrackingIdRoute = LiveTrackingIdRouteImport.update({
  id: '/live-tracking/$id',
  path: '/live-tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/merci': typeof MerciRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/rendez-vous': typeof RendezVousRoute
  '/services': typeof ServicesRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/zones': typeof ZonesRoute
  '/intervention/$ville': typeof InterventionVilleRoute
  '/live-tracking/$id': typeof LiveTrackingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/merci': typeof MerciRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/rendez-vous': typeof RendezVousRoute
  '/tarifs': typeof TarifsRoute
  '/zones': typeof ZonesRoute
  '/intervention/$ville': typeof InterventionVilleRoute
  '/live-tracking/$id': typeof LiveTrackingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/merci': typeof MerciRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/rendez-vous': typeof RendezVousRoute
  '/services': typeof ServicesRouteWithChildren
  '/tarifs': typeof TarifsRoute
  '/zones': typeof ZonesRoute
  '/intervention/$ville': typeof InterventionVilleRoute
  '/live-tracking/$id': typeof LiveTrackingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/mentions-legales'
    | '/merci'
    | '/politique-confidentialite'
    | '/rendez-vous'
    | '/services'
    | '/tarifs'
    | '/zones'
    | '/intervention/$ville'
    | '/live-tracking/$id'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/mentions-legales'
    | '/merci'
    | '/politique-confidentialite'
    | '/rendez-vous'
    | '/tarifs'
    | '/zones'
    | '/intervention/$ville'
    | '/live-tracking/$id'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/mentions-legales'
    | '/merci'
    | '/politique-confidentialite'
    | '/rendez-vous'
    | '/services'
    | '/tarifs'
    | '/zones'
    | '/intervention/$ville'
    | '/live-tracking/$id'
    | '/services/$slug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MerciRoute: typeof MerciRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  RendezVousRoute: typeof RendezVousRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TarifsRoute: typeof TarifsRoute
  ZonesRoute: typeof ZonesRoute
  InterventionVilleRoute: typeof InterventionVilleRoute
  LiveTrackingIdRoute: typeof LiveTrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervention/$ville': {
      id: '/intervention/$ville'
      path: '/intervention/$ville'
      fullPath: '/intervention/$ville'
      preLoaderRoute: typeof InterventionVilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-tracking/$id': {
      id: '/live-tracking/$id'
      path: '/live-tracking/$id'
      fullPath: '/live-tracking/$id'
      preLoaderRoute: typeof LiveTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MerciRoute: MerciRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  RendezVousRoute: RendezVousRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TarifsRoute: TarifsRoute,
  ZonesRoute: ZonesRoute,
  InterventionVilleRoute: InterventionVilleRoute,
  LiveTrackingIdRoute: LiveTrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
